### ISSUE TITLE
Newline affecting evaluation scores

### ISSUE THREAD

**Issue by shaoyent** [ankitshah009/Task-4-Large-scale-weakly-supervised-sound-event-detection-for-smart-cars#12]
Hi,

I'm getting zero scores when running `evaluation/TaskAEvaluate.py` due to newline not being correctly removed from groundtruth and predictions labels.

I suggest changing line 19 in `evaluation/Models.py` to `label = line.split("\t")[3].strip()` to better handle whitespace characters. May also need to add somewhere for predicted_labels.

Thanks.

**Comment by rohanbadlani** [comment]
Hi,

We have fixed the issue. Can you please check if its working for you now?

Regards,
Rohan
